# Reading a file with Open()

File handling is an essential aspect of programming, and Python provides built-in functions to interact with files. This guide will explore how to use Python's open function to read the text files (```'.txt'``` files).

# Objectives
1. Describe how to use the `open()` and `read()` Python functions to open and read the contents of a text file
2. Explain how to use the `with` statement in Python
3. Describe how to use the `readline()` function in Python
4. Explain how to use the `seek()` function to read specific character(s) in a text file

## Opening the file
There are two methods for opening the file using the file handling concept.

1. Using Python's open function
- Suppose we have a file named 'file.txt'. Python's open function creates a file object and accesses the data within a text file. It takes two primary parameters:
   1.  File path: The file path parameter consists of the filename and directory where the file is located.
   
   2. Mode: The mode parameter specifies the purpose of opening the file, such as 'r' for reading, 'w' for writing, or 'a' for appending.

```python
    # Open the file in read ('r') mode
    file = open('file.txt', 'r')
```

This line opens a file named 'file.txt' in read mode ('r'). It returns a file object, which is stored in the variable file. The 'r' mode indicates that the file will be **opened** for reading.


2. Using ```with``` statement
- To simplify file handling and ensure proper closure of files, Python provides the "with" statement. It automatically closes the file when operations within the indented block are completed. This is considered best practice when working with files.

```python

    # Open the file using 'with' in read ('r') mode
    with open('file.txt', 'r') as file:

```
This line opens a file named 'file.txt' in read mode ('r') using the with statement, which is a context manager. The file is automatically **closed** when the code block inside the with statement exits.

### Advantages of using the with statement
The key advantages of using the 'with' statement are:

- Automatic resource management: The file is guaranteed to be closed when you exit the with block, even if an exception occurs during processing.
- Cleaner and more concise code: You don't need to explicitly call close(), making your code more readable and less error-prone.

### 1. Reading the entire content

```Python

# Step 1: Open the file you want to read
with open('file.txt', 'r') as file:
    # Step 2: Use the read method to read the entire content of the file
    file_stuff = file.read()
    
    print(file_stuff)
```

### 2. Reading the content line by line

The ```readlines``` method reads the file line by line and stores each line as an element in a list. The order of lines in the list corresponds to their order in the file.

The ```readline``` method reads individual lines from the file. It can be called multiple times to read subsequent lines.

```Python
    file = open('file.txt', 'r')

    line1 = file.readline()  # Reads the first line
    line2 = file.readline()  # Reads the second line
```


#### Looping through lines: 
Typically, you use a loop to read lines until no more lines are left. t's like reading the entire book, line by line.

```Python
    
    while True:
    line = file.readline()
    if not line:
        break  # Stop when there are no more lines to read
    print(line)
    
    file.close()
    
```



# Writing Files with Open

We can open a file object using the method `write()` to save the text file to a list. To write to a file, the mode argument must be set to w. 

```python

exmp2 = '/Example2.txt'
with open(exmp2, 'w') as writefile:
    writefile.write("This is line A")
```
write with mulitiple linie

```python
with open(exmp2, 'w') as writefile:
    writefile.write("This is line A\n")
    writefile.write("This is line B\n")
```

write with list 

```python

Lines = ["This is line A\n", "This is line B\n", "This is line C\n"]
with open('/Example2.txt', 'w') as writefile:
    for line in Lines:
        print(line)
        writefile.write(line)

```

However, note that setting the mode to __w__ overwrites all the existing data in the file.

## Appending File
We can write to files without losing any of the existing data as follows by setting the mode argument to append: **a**.  you can append a new line as follows:

```python
# Write a new line to text file

with open('/Example2.txt', 'a') as testwritefile:
    testwritefile.write("This is line C\n")
    testwritefile.write("This is line D\n")
    testwritefile.write("This is line E\n")

```

## Additional modes
It's fairly ineffecient to open the file in **a** or **w** and then reopening it in **r** to read any lines. Luckily we can access the file in the following modes:
- **r+** : Reading and writing. Cannot truncate the file.
- **w+** : Writing and reading. Truncates the file.
- **a+** : Appending and Reading. Creates a new file, if none exists.
You dont have to dwell on the specifics of each mode for this lab. 


In [1]:
import numpy as np
x = [1,2]
y =np.array(x)

In [4]:
x*2

[1, 2, 1, 2]

In [5]:
y*2

array([2, 4])

In [8]:
x+y

array([2, 4])

In [9]:
max(x)

2

In [10]:
max(y)

2

In [13]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[2,1],[1,2]]) 

Z=np.dot(X,Y) 

In [14]:
Z

array([[2, 1],
       [1, 2]])